Add 1.4.0 migration guide.
ktorio/ktorio.github.io pull request #301
Opened 2020-08-24 11:19 UTC by e5l

Fix #KTOR-931

2020-08-24 11:26 UTC, Stexxe commented
> ```
> Fix #KTOR-931
> ```

Может лучше делать #KTOR-931 ссылкой? [KTOR-931](https://youtrack.jetbrains.com/issue/KTOR-931)

2020-08-24 11:41 UTC, e5l commented
Sure, done

2020-08-24 11:42 UTC, Stexxe requested changes

2020-08-24 11:42 UTC, Stexxe commented on quickstart/migration/1.4.0.md
> +{: #1.4.0 }
Github rich text previewer shows this as `{: #1.4.0 }`

2020-08-24 11:42 UTC, Stexxe commented on quickstart/migration/1.4.0.md
> +* Upgrade to kotlin 1.4.0
Why do we need to have a list of changes in the migration guide?

2020-08-24 11:42 UTC, Stexxe commented on quickstart/migration/1.4.0.md
> +* The `-native` suffix is obsolete dut to migration to HMPP. The common artifact can be used instead. For example the `kotlinx-client-core-native` -> `ktor-client-core`.
Typo `due`

2020-08-24 11:42 UTC, Stexxe commented on quickstart/migration/1.4.0.md
> +* Maven users can fail to resolve `ktor-client-cio` because it's common from 1.4.0. You can use `ktor-client-cio-jvm` instead. Gradle users can use any artifact(due to metadata).
I think `can fail` is not appropriate here — `may fail` or `will fail` is more suitable, cc @hhariri.

2020-08-24 11:42 UTC, Stexxe commented on quickstart/migration/1.4.0.md
> +* Maven users can fail to resolve `ktor-client-cio` because it's common from 1.4.0. You can use `ktor-client-cio-jvm` instead. Gradle users can use any artifact(due to metadata).
Space before `(due to metadata)` is missing.

2020-08-24 11:42 UTC, Stexxe commented on quickstart/migration/1.4.0.md
> +* The `-native` suffix is obsolete dut to migration to HMPP. The common artifact can be used instead. For example the `kotlinx-client-core-native` -> `ktor-client-core`.
This paragraph is difficult to read because it contains many small sentences.

2020-08-24 12:46 UTC, e5l commented on quickstart/migration/1.4.0.md
> +* Upgrade to kotlin 1.4.0
We had them for the previous: https://ktor.io/quickstart/migration/1.3.0.html
@hhariri what do you think?

2020-08-24 12:46 UTC, e5l commented on quickstart/migration/1.4.0.md
> +{: #1.4.0 }
It's a jekyll syntax

2020-08-24 12:46 UTC, e5l commented on quickstart/migration/1.4.0.md
> +* The `-native` suffix is obsolete dut to migration to HMPP. The common artifact can be used instead. For example the `kotlinx-client-core-native` -> `ktor-client-core`.
Thanks

2020-08-24 12:54 UTC, Stexxe commented on quickstart/migration/1.4.0.md
> +* Upgrade to kotlin 1.4.0
Maybe we should make this section hideable/scrollable or less perceptible than the guide.

2020-08-24 13:03 UTC, e5l commented on quickstart/migration/1.4.0.md
> +* The `-native` suffix is obsolete dut to migration to HMPP. The common artifact can be used instead. For example the `kotlinx-client-core-native` -> `ktor-client-core`.
Could you tell me if you have an idea of rewriting it?

2020-08-24 14:40 UTC, Stexxe commented on quickstart/migration/1.4.0.md
> +* The `-native` suffix is obsolete dut to migration to HMPP. The common artifact can be used instead. For example the `kotlinx-client-core-native` -> `ktor-client-core`.
I suggest asking @hhariri how to better structure it.

2020-08-26 12:24 UTC, hhariri commented on quickstart/migration/1.4.0.md
> +* Upgrade to kotlin 1.4.0
We're eventually going to move this to What's New on the site. Not sure it's needed in Migration Guide.

2020-08-26 12:27 UTC, hhariri commented on quickstart/migration/1.4.0.md
> +* The `-native` suffix is obsolete dut to migration to HMPP. The common artifact can be used instead. For example the `kotlinx-client-core-native` -> `ktor-client-core`.
The `-native` suffix is now obsolete as per the new Kotlin Multiplatform Project approach, which allows the use of common artifacts. This means that for instance `kotlinx-client-core-native` would be replaced with `ktor-client-core`.

2020-08-26 12:56 UTC, e5l commented on quickstart/migration/1.4.0.md
> +* The `-native` suffix is obsolete dut to migration to HMPP. The common artifact can be used instead. For example the `kotlinx-client-core-native` -> `ktor-client-core`.
Thanks

2020-08-26 12:58 UTC, merged